name = "lisbon-ai-travel"
pages_build_output_dir = ".next"

[vars]
API_KEY = ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

[env.production]
routes = [
  { pattern = "lisbon-ai.samrhea.com", custom_domain = true }
]

[env.production.vars]
ENVIRONMENT = "production"
