name = "lisbon-ai"
compatibility_date = "2023-05-18"

[site]
bucket = ".next/static"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[env.production]
routes = [
  { pattern = "lisbon-ai.samrhea.com", custom_domain = true }
]

[env.production.vars]
ENVIRONMENT = "production"
