
name: Prod Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.JS environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Log Details
        run: npm version

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    
      - name: Install Wrangler
        run: npm install -g wrangler

      - name: config wrangler
        env:
          CLOUDFLARE_DEPLOY_TOKEN: ${{ secrets.CLOUDFLARE_DEPLOY_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages deploy .next --project-name=lisbon-ai-travel
